spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://dev-90706258.okta.com/oauth2/default"

  cloud:
    gateway:
      routes:
        - id: root-health-endpoint
          uri: http://localhost:8080
          predicates:
              - Path=/
          filters:
            - SetStatus=200

        - id: add-header
          uri: "http://localhost:8085"
          predicates:
            - Path=/products
          filters:
            - Authorize
            #- ExtractClaim=sub,MY-NAME
        - id: userId
          uri: "http://users-service:80/testUser"
          predicates:
            - Path=/api/users
          filters:
            - SetStatus=200
logging:
  level:
    org.springframework.security: DEBUG