spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${OKTA_RESOURCE_SERVER_URI}"

  cloud:
    gateway:
      routes:
        - id: plain-text-response
          uri: "no://localhost"
          predicates:
            - Path=/
          filters:
            - SetStatus=204

        - id: plain-text-response
          uri: "no://localhost"
          predicates:
            - Path=/api
          filters:
            - SetStatus=204

        - id: allow-inline-hook-access
          uri: "forward:/inlineHook"
          predicates:
            - Path=/api/inlineHook

        - id: secure-portfolio-requests
          uri: "${USERS_BASE_URL}"
          predicates:
            - Path=/api/user/**
          filters:
            - Authorize
            - ClaimToHeader=userId,X-User-Id
            - RewritePath=/api/user(?<segment>/.*)?, /user${segment}

autoinvestor:
  client:
    users:
      url: "${USERS_BASE_URL}"