spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://dev-90706258.okta.com/oauth2/default"

  cloud:
    gateway:
      routes:
        - id: plain-text-response
          uri: "no://localhost"
          predicates:
            - Path=/
          filters:
            - SetStatus=204

        - id: allow-inline-hook-access
          uri: "forward:/internal-endpoint"
          predicates:
            - Path=/api/inlineHook

        - id: secure-portfolio-requests
          uri: "http://portfolio-service"
          predicates:
            - Path=/api/portfolio/**
          filters:
            - Authorize
            - ClaimToHeader=userId,X-User-Id
            - RewritePath=/(?<segment>.*), /${segment}