autoinvestor:
  okta:
    hookAuthHeaderName: "${OKTA_HOOK_AUTH_HEADER_NAME}"
    hookAuthHeaderValue: "${OKTA_HOOK_AUTH_HEADER_VALUE}"
  client:
    users:
      url: "${USERS_BASE_URL}"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${OKTA_DOMAIN}/oauth2/default
      client:
        registration:
          okta:
            client-id: ${OKTA_CLIENT_ID}
            client-secret: ${OKTA_CLIENT_SECRET}
            provider: okta
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/api/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          okta:
            issuer-uri: https://${OKTA_DOMAIN}/oauth2/default
            authorization-uri: https://${OKTA_DOMAIN}/oauth2/default/v1/authorize
            token-uri: https://${OKTA_DOMAIN}/oauth2/default/v1/token
            user-info-uri: https://${OKTA_DOMAIN}/oauth2/default/v1/userinfo
            user-name-attribute: sub

  cloud:
    gateway:
      routes:
        - id: plain-text-response
          uri: "no://localhost"
          predicates:
            - Path=/
          filters:
            - SetStatus=200

        - id: plain-text-response
          uri: "no://localhost"
          predicates:
            - Path=/api
          filters:
            - SetStatus=200

        - id: oauth2-auth
          uri: http://localhost:8080
          predicates:
            - Path=/api/oauth2/**
          filters:
            - RewritePath=/api/oauth2/(?<segment>.*), /oauth2/${segment}

        - id: login-auth
          uri: http://localhost:8080
          predicates:
            - Path=/api/login/**
          filters:
            - RewritePath=/api/login/(?<segment>.*), /login/${segment}

        - id: get-user-endpoint
          uri: "${USERS_BASE_URL}"
          predicates:
            - Path=/api/user
            - Method=GET
          filters:
            - ClaimToHeader=userId,X-User-Id
            - RewritePath=/api/user,/user
