autoinvestor:
  domain: ${AUTOINVESTOR_URI}
  okta:
    clientId: ${OKTA_CLIENT_ID}
    clientSecret: ${OKTA_CLIENT_SECRET}
    redirectUri: "${autoinvestor.domain}/api/auth/callback"
  client:
    users:
      url: "${USERS_BASE_URL}"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${OKTA_RESOURCE_SERVER_URI}"

  cloud:
    gateway:
      routes:
        - id: plain-text-response
          uri: "no://localhost"
          predicates:
            - Path=/
          filters:
            - SetStatus=204

        - id: plain-text-response
          uri: "no://localhost"
          predicates:
            - Path=/api
          filters:
            - SetStatus=204

        - id: okta-login-redirect
          uri: "forward:/auth/login"
          predicates:
            - Path=/api/auth/login

        - id: okta-login-redirect
          uri: "forward:/auth/callback"
          predicates:
            - Path=/api/auth/callback

        - id: allow-inline-hook-access
          uri: "forward:/inlineHook"
          predicates:
            - Path=/api/inlineHook

        - id: secure-portfolio-requests
          uri: "${USERS_BASE_URL}"
          predicates:
            - Path=/api/user/**
          filters:
            - Authorize
            - ClaimToHeader=userId,X-User-Id
            - RewritePath=/api/user(?<segment>/.*)?, /user${segment}
