autoinvestor:
  client:
    users:
      url: "${USERS_BASE_URL}"
    portfolio:
      url: "${PORTFOLIO_BASE_URL}"
    market-feeling:
      url: "${MARKET_FEELING_BASE_URL}"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${OKTA_DOMAIN}/oauth2/default
      client:
        registration:
          okta:
            client-id: ${OKTA_CLIENT_ID}
            client-secret: ${OKTA_CLIENT_SECRET}
            provider: okta
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/api/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          okta:
            issuer-uri: https://${OKTA_DOMAIN}/oauth2/default
            authorization-uri: https://${OKTA_DOMAIN}/oauth2/default/v1/authorize
            token-uri: https://${OKTA_DOMAIN}/oauth2/default/v1/token
            user-info-uri: https://${OKTA_DOMAIN}/oauth2/default/v1/userinfo
            user-name-attribute: sub

  cloud:
    gateway:
      routes:
        - id: plain-text-response
          uri: "no://localhost"
          predicates:
            - Path=/
          filters:
            - SetStatus=200

        - id: oauth2-auth
          uri: http://localhost:8080
          predicates:
            - Path=/api/oauth2/**
          filters:
            - RewritePath=/api/(?<segment>.*),/${segment}

        - id: login-auth
          uri: http://localhost:8080
          predicates:
            - Path=/api/login/**
          filters:
            - RewritePath=/api/(?<segment>.*),/${segment}

        - id: get-user-endpoint
          uri: "${USERS_BASE_URL}"
          predicates:
            - Path=/api/user
            - Method=GET,PUT
          filters:
            - ClaimToHeader=userId,X-User-Id
            - RewritePath=/api/(?<segment>.*),/${segment}

        - id: get-all-assets-endpoint
          uri: "${CORE_BASE_URL}"
          predicates:
            - Path=/api/assets
            - Method=GET
          filters:
            - ClaimToHeader=userId,X-User-Id
            - RewritePath=/api/(?<segment>.*),/${segment}

        - id: get-asset-endpoint
          uri: "${CORE_BASE_URL}"
          predicates:
            - Path=/api/assets/*
            - Method=GET
          filters:
            - ClaimToHeader=userId,X-User-Id
            - RewritePath=/api/(?<segment>.*),/${segment}

        - id: get-asset-price-endpoint
          uri: "${CORE_BASE_URL}"
          predicates:
            - Path=/api/assets/*/price
            - Method=GET
          filters:
            - ClaimToHeader=userId,X-User-Id
            - RewritePath=/api/(?<segment>.*),/${segment}

        - id: get-news-endpoint
          uri: http://localhost:8080
          predicates:
            - Path=/api/news
            - Method=GET
          filters:
            - ClaimToHeader=userId,X-User-Id
            - RewritePath=/api/news, /internal/news

        - id: get-decisions-endpoint
          uri: "${DECISION_MAKING_BASE_URL}"
          predicates:
            - Path=/api/decisions
            - Method=GET
          filters:
            - ClaimToHeader=userId,X-User-Id
            - RewritePath=/api/(?<segment>.*),/${segment}

        - id: get-alerts-endpoint
          uri: "${ALERTS_BASE_URL}"
          predicates:
            - Path=/api/alerts
            - Method=GET
          filters:
            - ClaimToHeader=userId,X-User-Id
            - RewritePath=/api/(?<segment>.*),/${segment}

        - id: portfolio-endpoints
          uri: "${PORTFOLIO_BASE_URL}"
          predicates:
            - Path=/api/portfolio/holdings
            - Method=GET,POST,PUT,DELETE
          filters:
            - ClaimToHeader=userId,X-User-Id
            - RewritePath=/api/(?<segment>.*),/${segment}