autoinvestor:
  baseUrl: ${AUTOINVESTOR_BASE_URL}
  tokenCookieName: "access_token"
  okta:
    redirectUri: "${AUTOINVESTOR_BASE_URL}/api/auth/callback"
    hookAuthHeaderName: "${OKTA_HOOK_AUTH_HEADER_NAME}"
    hookAuthHeaderValue: "${OKTA_HOOK_AUTH_HEADER_VALUE}"
  client:
    users:
      url: "${USERS_BASE_URL}"
    oauth2:
      url: "https://${OKTA_DOMAIN}/oauth2/default/v1"
      authorization:
        basic:
          username: ${OKTA_CLIENT_ID}
          password: ${OKTA_CLIENT_SECRET}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://${OKTA_DOMAIN}/oauth2/default/v1"

  cloud:
    gateway:
      routes:
        - id: plain-text-response
          uri: "no://localhost"
          predicates:
            - Path=/
          filters:
            - SetStatus=200

        - id: plain-text-response
          uri: "no://localhost"
          predicates:
            - Path=/api
          filters:
            - SetStatus=200

        - id: register-hook
          uri: "forward:/hook/register"
          predicates:
            - Path=/api/hook/register
          filters:
            - AuthorizeHook

        - id: token-hook
          uri: "forward:/hook/token"
          predicates:
            - Path=/api/hook/token
          filters:
            - AuthorizeHook

        - id: okta-login-redirect
          uri: "forward:/auth/login"
          predicates:
            - Path=/api/auth/login

        - id: okta-login-callback
          uri: "forward:/auth/callback"
          predicates:
            - Path=/api/auth/callback

        - id: get-user-endpoint
          uri: "${USERS_BASE_URL}"
          predicates:
            - Path=/api/user
            - Method=GET
          filters:
            - Authorize
            - ClaimToHeader=userId,X-User-Id
            - RewritePath=/api/user,/user
